### ISSUE TITLE
Feature request..... Enable live wallpapers option

### ISSUE THREAD

**Issue by AndressaLamm** [XOSP/utilities-xosp-bugtracker#12]
Hi.... I really love this rom but i still miss using KLWP. Is there any way to make live wallpapers work in this rom?

**Comment by nilac8991** [comment]
Live wallpapers aren't included

**Comment by AndressaLamm** [comment]
I know that live wallpapers aren't included in this rom. But i will like very much if this will be possible. Why the reason that isn't included?

**Comment by nilac8991** [comment]
Not many users are using it. That's why, and it has been out since MM days
