### ISSUE TITLE
Improvements to xosp

### ISSUE THREAD

**Issue by deccan451** [XOSP/utilities-xosp-bugtracker#14]
1. Remove nfc tile for non nfc devices and add sync tile 
2. Theme/ add icon's (calculator,  contact's,  dailer etc) Xperia looks 
3. Fix priority mode messages sound with notification and lockscreen weather

**Comment by deccan451** [comment]
4. Fix select network notification on every reboot

**Comment by nilac8991** [comment]
One request per issue, not 4
