### ISSUE TITLE
XOSPChangeLOG and Delta Updates 

### ISSUE THREAD

**Issue by allellee** [XOSP/utilities-xosp-bugtracker#15]
Is there the possibility to put and compile the ROM to flash by XOSPChangeLOG app in the Micro SD Card? Or an option to choose where to do it. 
Devices with 8GB of ROM have not enough space to update (new compliled build is up to 800MB plus the delta and the old build). Thanks

**Comment by out386** [comment]
Sorry, that's just not possible right now. It will be fixed soon.
