### ISSUE TITLE
Tap-to-wake issue

### ISSUE THREAD

**Issue by and-live** [XOSP/utilities-xosp-bugtracker#22]
When "Tap to wake" is enabled along with "Prevent accidental wake-up" option, there is an issue when you make a call. If you accidentally double-tap phone screen with your cheek when the phone is close to your head, call is hanged immediately. The latter option should check both proximity sensor and phone call mode, but it only do the first thing.

**Comment by nilac8991** [comment]
Can you grab a logcat of this?

**Comment by and-live** [comment]
[logcat_and_device_info.zip](https://github.com/XOSP-Project/utilities-xosp-bugtracker/files/1138712/logcat_and_device_info.zip)

Another one detail: "Power button ends call" option must be turned on as well.

**Comment by nilac8991** [comment]
Thanks, will look into it in the next days
