### ISSUE TITLE
volume buttons don't work when screen is off

### ISSUE THREAD

**Issue by csendre** [XOSP/utilities-xosp-bugtracker#4]
The volume buttons don't work when the screen is turned off; as soon as the screen is turned on, functionality returns. This is somewhat annoying when using the phone as music player.

**Comment by nilac8991** [comment]
Yeah I confirm it but this happens only when the Volume Buttons are used for Media Player

**Comment by Siphonay** [comment]
I think this is not a bug, it is caused by the feature that makes the tracks change when volume buttons are long-pressed when the screen is off. Disabling it in the sound settings makes them work again.

**Comment by csendre** [comment]
It is still a bug, this feature shouldn't interfere with volume. In LOS on the FM Radio app long press for next station and volume both work (didn't try media player)

**Comment by nilac8991** [comment]
Covered by these commits: 
https://github.com/XOSP-Project/android_frameworks_base/commit/434cf40ee49eb6c142784d236ef3e8790c852944
https://github.com/XOSP-Project/android_frameworks_base/commit/039781d275c9db95c1a53c1a3c308a7fe33b74ef
